export const errorMap = {
    1000: 'wrong credential',
    1001: 'api key invalid ',
    1002: 'insufficient balance',
    1003: 'username has been used',
    1004: 'user not found',
    1005: 'wrong referal code',
    1006: 'user already assigned to admin',
    2000: 'product not found',
    2001: 'product price same or less than supplier price',
    2002: 'product price is lower than actual price',
    2003: 'admin product price same or less than actual price',
    2004: 'admin not allowed to sell product',
    4000: 'missing request payload' + ':' + ' ',
    4001: 'wrong request payload' + ':' + ' ',
    4002: 'missing api key',
    4003: 'invalid api key',
    4004: 'tx not found',
    4005: 'expired tx',
    4006: 'duplicate customer_no found',
    4007: 'cannot add product to non customer',
    4008: 'failed updating product',
    4009: 'value already exist' + ':' + ' ',
    4010: 'value not found' + ':' + ' ',
    5000: 'something wrong, please contact support'
  };