version: '3.8'

services:
  # postgres:
  #   image: postgres:17
  #   container_name: ecom_database
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: P@ssw0rd4dM!n
  #     POSTGRES_DB: ecom_transaction
  #   ports:
  #     - '5430:5432'
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data # Bind to a local directory
  #   restart: unless-stopped
  #   networks:
  #     - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6380:6379'
    volumes:
      - ./redis_data:/data # Bind to a local directory
    restart: unless-stopped
    command: |
      redis-server
      --requirepass your_secure_password
      --appendonly yes
      --appendfsync everysec
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
